# Use Cypress base image with pre-installed headless browsers
FROM cypress/included:latest

LABEL container.name="ttg-tests"
LABEL maintainer="m0labs"
LABEL description="a docker container which executes cypress e2e tests"


# Set working directory
WORKDIR /app

# Install Python, required by node-gyp
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean

# Install pm2 to run the app in the background
RUN npm install -g pm2

# Copy the application into the container
COPY package.json yarn.lock /app/

# Install any dependencies your application requires (if needed)
# speedup build
RUN yarn install

COPY . /app

# Expose ports? only internal ports. no need to expose
# EXPOSE 3000
# EXPOSE 8545

## Start the application service on port 3000
# CMD ["pm2", "start", "ecosystem.config.js"]

# Default entry point
ENTRYPOINT ["cypress", "run"]
