query standardGovernorVoteCasts {
  voteCasts(first: 10000) {
    proposalId
    support
    id
    reason
    blockTimestamp
    blockNumber
    proposalId
    reason
    support
    transactionHash
    voter
    weight
  }
}
