// Generated by @wagmi/cli@0.1.15 on 11/27/2023 at 1:56:04 PM
import {
  getContract,
  GetContractArgs,
  readContract,
  ReadContractConfig,
  writeContract,
  WriteContractArgs,
  WriteContractPreparedArgs,
  WriteContractUnpreparedArgs,
  prepareWriteContract,
  PrepareWriteContractConfig,
  watchContractEvent,
  WatchContractEventConfig,
  WatchContractEventCallback,
} from "@wagmi/core";

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DualGovernor
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const dualGovernorABI = [
  {
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [
      { name: "registrar_", internalType: "address", type: "address" },
      { name: "powerToken_", internalType: "address", type: "address" },
      { name: "zeroToken_", internalType: "address", type: "address" },
      { name: "vault_", internalType: "address", type: "address" },
      {
        name: "allowedCashTokens_",
        internalType: "address[]",
        type: "address[]",
      },
      { name: "proposalFee_", internalType: "uint256", type: "uint256" },
      {
        name: "maxTotalZeroRewardPerActiveEpoch_",
        internalType: "uint256",
        type: "uint256",
      },
      {
        name: "powerTokenThresholdRatio_",
        internalType: "uint16",
        type: "uint16",
      },
      {
        name: "zeroTokenThresholdRatio_",
        internalType: "uint16",
        type: "uint16",
      },
    ],
  },
  { type: "error", inputs: [], name: "AlreadyVoted" },
  { type: "error", inputs: [], name: "EpochHasNoProposals" },
  {
    type: "error",
    inputs: [{ name: "data", internalType: "bytes", type: "bytes" }],
    name: "ExecutionFailed",
  },
  {
    type: "error",
    inputs: [
      {
        name: "state",
        internalType: "enum IGovernor.ProposalState",
        type: "uint8",
      },
    ],
    name: "FeeNotDestinedForVault",
  },
  { type: "error", inputs: [], name: "InvalidCallDatasLength" },
  { type: "error", inputs: [], name: "InvalidCashToken" },
  { type: "error", inputs: [], name: "InvalidPowerTokenAddress" },
  { type: "error", inputs: [], name: "InvalidProposalType" },
  { type: "error", inputs: [], name: "InvalidSignature" },
  { type: "error", inputs: [], name: "InvalidTarget" },
  { type: "error", inputs: [], name: "InvalidTargetsLength" },
  { type: "error", inputs: [], name: "InvalidValue" },
  { type: "error", inputs: [], name: "InvalidValuesLength" },
  { type: "error", inputs: [], name: "InvalidZeroTokenAddress" },
  { type: "error", inputs: [], name: "MalleableSignature" },
  { type: "error", inputs: [], name: "NoAllowedCashTokens" },
  { type: "error", inputs: [], name: "NoProposalFee" },
  { type: "error", inputs: [], name: "NotSelf" },
  { type: "error", inputs: [], name: "ProposalCannotBeExecuted" },
  { type: "error", inputs: [], name: "ProposalDoesNotExist" },
  { type: "error", inputs: [], name: "ProposalExists" },
  {
    type: "error",
    inputs: [
      {
        name: "state",
        internalType: "enum IGovernor.ProposalState",
        type: "uint8",
      },
    ],
    name: "ProposalNotActive",
  },
  {
    type: "error",
    inputs: [
      { name: "nonce", internalType: "uint256", type: "uint256" },
      { name: "currentNonce", internalType: "uint256", type: "uint256" },
    ],
    name: "ReusedNonce",
  },
  {
    type: "error",
    inputs: [
      { name: "deadline", internalType: "uint256", type: "uint256" },
      { name: "timestamp", internalType: "uint256", type: "uint256" },
    ],
    name: "SignatureExpired",
  },
  {
    type: "error",
    inputs: [
      { name: "account", internalType: "address", type: "address" },
      { name: "signer", internalType: "address", type: "address" },
    ],
    name: "SignerMismatch",
  },
  { type: "error", inputs: [], name: "ZeroCashTokenAddress" },
  { type: "error", inputs: [], name: "ZeroRegistrarAddress" },
  { type: "error", inputs: [], name: "ZeroVaultAddress" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "cashToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "CashTokenSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "thresholdRatio",
        internalType: "uint16",
        type: "uint16",
        indexed: false,
      },
    ],
    name: "PowerTokenThresholdRatioSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "proposalId",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "proposer",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      {
        name: "targets",
        internalType: "address[]",
        type: "address[]",
        indexed: false,
      },
      {
        name: "values",
        internalType: "uint256[]",
        type: "uint256[]",
        indexed: false,
      },
      {
        name: "signatures",
        internalType: "string[]",
        type: "string[]",
        indexed: false,
      },
      {
        name: "calldatas",
        internalType: "bytes[]",
        type: "bytes[]",
        indexed: false,
      },
      {
        name: "voteStart",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "voteEnd",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "description",
        internalType: "string",
        type: "string",
        indexed: false,
      },
    ],
    name: "ProposalCreated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "proposalId",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "ProposalExecuted",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "proposalId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "cashToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "proposalFee",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "ProposalFeeSentToVault",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "proposalFee",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "ProposalFeeSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "voter",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "proposalId",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      { name: "support", internalType: "uint8", type: "uint8", indexed: false },
      {
        name: "weight",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "reason",
        internalType: "string",
        type: "string",
        indexed: false,
      },
    ],
    name: "VoteCast",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "thresholdRatio",
        internalType: "uint16",
        type: "uint16",
        indexed: false,
      },
    ],
    name: "ZeroTokenThresholdRatioSet",
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "BALLOTS_TYPEHASH",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "BALLOTS_WITH_REASON_TYPEHASH",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "BALLOT_TYPEHASH",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "BALLOT_WITH_REASON_TYPEHASH",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [],
    name: "CLOCK_MODE",
    outputs: [{ name: "clockMode_", internalType: "string", type: "string" }],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [],
    name: "COUNTING_MODE",
    outputs: [
      { name: "countingMode_", internalType: "string", type: "string" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "DOMAIN_SEPARATOR",
    outputs: [
      { name: "domainSeparator_", internalType: "bytes32", type: "bytes32" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "ONE",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "list_", internalType: "bytes32", type: "bytes32" },
      { name: "accountToAdd_", internalType: "address", type: "address" },
      { name: "accountToRemove_", internalType: "address", type: "address" },
    ],
    name: "addAndRemoveFromList",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "list_", internalType: "bytes32", type: "bytes32" },
      { name: "account_", internalType: "address", type: "address" },
    ],
    name: "addToList",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "cashToken",
    outputs: [{ name: "cashToken_", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "proposalId_", internalType: "uint256", type: "uint256" },
      { name: "support_", internalType: "uint8", type: "uint8" },
    ],
    name: "castVote",
    outputs: [{ name: "weight_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "proposalId_", internalType: "uint256", type: "uint256" },
      { name: "support_", internalType: "uint8", type: "uint8" },
      { name: "v_", internalType: "uint8", type: "uint8" },
      { name: "r_", internalType: "bytes32", type: "bytes32" },
      { name: "s_", internalType: "bytes32", type: "bytes32" },
    ],
    name: "castVoteBySig",
    outputs: [{ name: "weight_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "proposalId_", internalType: "uint256", type: "uint256" },
      { name: "support_", internalType: "uint8", type: "uint8" },
      { name: "", internalType: "string", type: "string" },
    ],
    name: "castVoteWithReason",
    outputs: [{ name: "weight_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "proposalId_", internalType: "uint256", type: "uint256" },
      { name: "support_", internalType: "uint8", type: "uint8" },
      { name: "reason_", internalType: "string", type: "string" },
      { name: "v_", internalType: "uint8", type: "uint8" },
      { name: "r_", internalType: "bytes32", type: "bytes32" },
      { name: "s_", internalType: "bytes32", type: "bytes32" },
    ],
    name: "castVoteWithReasonBySig",
    outputs: [{ name: "weight_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "proposalIds_", internalType: "uint256[]", type: "uint256[]" },
      { name: "supports_", internalType: "uint8[]", type: "uint8[]" },
    ],
    name: "castVotes",
    outputs: [{ name: "weight_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "proposalIds_", internalType: "uint256[]", type: "uint256[]" },
      { name: "supports_", internalType: "uint8[]", type: "uint8[]" },
      { name: "v_", internalType: "uint8", type: "uint8" },
      { name: "r_", internalType: "bytes32", type: "bytes32" },
      { name: "s_", internalType: "bytes32", type: "bytes32" },
    ],
    name: "castVotesBySig",
    outputs: [{ name: "weight_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "proposalIds_", internalType: "uint256[]", type: "uint256[]" },
      { name: "supports_", internalType: "uint8[]", type: "uint8[]" },
      { name: "", internalType: "string[]", type: "string[]" },
    ],
    name: "castVotesWithReason",
    outputs: [{ name: "weight_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "proposalIds_", internalType: "uint256[]", type: "uint256[]" },
      { name: "supports_", internalType: "uint8[]", type: "uint8[]" },
      { name: "reasons_", internalType: "string[]", type: "string[]" },
      { name: "v_", internalType: "uint8", type: "uint8" },
      { name: "r_", internalType: "bytes32", type: "bytes32" },
      { name: "s_", internalType: "bytes32", type: "bytes32" },
    ],
    name: "castVotesWithReasonBySig",
    outputs: [{ name: "weight_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "clock",
    outputs: [{ name: "clock_", internalType: "uint48", type: "uint48" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "list_", internalType: "bytes32", type: "bytes32" },
      { name: "accountToAdd_", internalType: "address", type: "address" },
      { name: "accountToRemove_", internalType: "address", type: "address" },
    ],
    name: "emergencyAddAndRemoveFromList",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "list_", internalType: "bytes32", type: "bytes32" },
      { name: "account_", internalType: "address", type: "address" },
    ],
    name: "emergencyAddToList",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "list_", internalType: "bytes32", type: "bytes32" },
      { name: "account_", internalType: "address", type: "address" },
    ],
    name: "emergencyRemoveFromList",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "newProposalFee_", internalType: "uint256", type: "uint256" },
    ],
    name: "emergencySetProposalFee",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "key_", internalType: "bytes32", type: "bytes32" },
      { name: "value_", internalType: "bytes32", type: "bytes32" },
    ],
    name: "emergencyUpdateConfig",
    outputs: [],
  },
  {
    stateMutability: "payable",
    type: "function",
    inputs: [
      { name: "", internalType: "address[]", type: "address[]" },
      { name: "", internalType: "uint256[]", type: "uint256[]" },
      { name: "callDatas_", internalType: "bytes[]", type: "bytes[]" },
      { name: "", internalType: "bytes32", type: "bytes32" },
    ],
    name: "execute",
    outputs: [
      { name: "proposalId_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "proposalId_", internalType: "uint256", type: "uint256" }],
    name: "getProposal",
    outputs: [
      {
        name: "proposalType_",
        internalType: "enum IDualGovernor.ProposalType",
        type: "uint8",
      },
      { name: "voteStart_", internalType: "uint16", type: "uint16" },
      { name: "voteEnd_", internalType: "uint16", type: "uint16" },
      { name: "executed_", internalType: "bool", type: "bool" },
      {
        name: "state_",
        internalType: "enum IGovernor.ProposalState",
        type: "uint8",
      },
      { name: "thresholdRatio_", internalType: "uint16", type: "uint16" },
      { name: "noVotes_", internalType: "uint256", type: "uint256" },
      { name: "yesVotes_", internalType: "uint256", type: "uint256" },
      { name: "proposer_", internalType: "address", type: "address" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "timepoint_", internalType: "uint256", type: "uint256" },
    ],
    name: "getVotes",
    outputs: [{ name: "weight_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "proposalId_", internalType: "uint256", type: "uint256" },
      { name: "account_", internalType: "address", type: "address" },
    ],
    name: "hasVoted",
    outputs: [{ name: "hasVoted_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "voter_", internalType: "address", type: "address" },
      { name: "epoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "hasVotedOnAllStandardProposals",
    outputs: [{ name: "hasVoted_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "callData_", internalType: "bytes", type: "bytes" }],
    name: "hashProposal",
    outputs: [
      { name: "proposalId_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "", internalType: "address[]", type: "address[]" },
      { name: "", internalType: "uint256[]", type: "uint256[]" },
      { name: "callDatas_", internalType: "bytes[]", type: "bytes[]" },
      { name: "", internalType: "bytes32", type: "bytes32" },
    ],
    name: "hashProposal",
    outputs: [
      { name: "proposalId_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "token_", internalType: "address", type: "address" }],
    name: "isAllowedCashToken",
    outputs: [{ name: "isAllowed_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [],
    name: "markEpochActive",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "maxTotalZeroRewardPerActiveEpoch",
    outputs: [{ name: "reward_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "name",
    outputs: [{ name: "name_", internalType: "string", type: "string" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "account_", internalType: "address", type: "address" }],
    name: "nonces",
    outputs: [{ name: "nonce_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "epoch_", internalType: "uint256", type: "uint256" }],
    name: "numberOfStandardProposalsAt",
    outputs: [{ name: "count_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "epoch_", internalType: "uint256", type: "uint256" },
      { name: "voter_", internalType: "address", type: "address" },
    ],
    name: "numberOfStandardProposalsVotedOnAt",
    outputs: [{ name: "count_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "powerToken",
    outputs: [
      { name: "powerToken_", internalType: "address", type: "address" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "powerTokenThresholdRatio",
    outputs: [
      { name: "thresholdRatio_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "proposalId_", internalType: "uint256", type: "uint256" }],
    name: "proposalDeadline",
    outputs: [{ name: "deadline_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "proposalFee",
    outputs: [
      { name: "proposalFee_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "proposalId_", internalType: "uint256", type: "uint256" }],
    name: "proposalProposer",
    outputs: [{ name: "proposer_", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "proposalId_", internalType: "uint256", type: "uint256" }],
    name: "proposalSnapshot",
    outputs: [{ name: "snapshot_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "targets_", internalType: "address[]", type: "address[]" },
      { name: "values_", internalType: "uint256[]", type: "uint256[]" },
      { name: "callDatas_", internalType: "bytes[]", type: "bytes[]" },
      { name: "description_", internalType: "string", type: "string" },
    ],
    name: "propose",
    outputs: [
      { name: "proposalId_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [{ name: "timepoint_", internalType: "uint256", type: "uint256" }],
    name: "quorum",
    outputs: [{ name: "quorum_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "registrar",
    outputs: [{ name: "registrar_", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "list_", internalType: "bytes32", type: "bytes32" },
      { name: "account_", internalType: "address", type: "address" },
    ],
    name: "removeFromList",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [],
    name: "resetToPowerHolders",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [],
    name: "resetToZeroHolders",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [{ name: "proposalId_", internalType: "uint256", type: "uint256" }],
    name: "sendProposalFeeToVault",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "newCashToken_", internalType: "address", type: "address" },
      { name: "newProposalFee_", internalType: "uint256", type: "uint256" },
    ],
    name: "setCashToken",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "newThresholdRatio_", internalType: "uint16", type: "uint16" },
    ],
    name: "setPowerTokenThresholdRatio",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "newProposalFee_", internalType: "uint256", type: "uint256" },
    ],
    name: "setProposalFee",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "newThresholdRatio_", internalType: "uint16", type: "uint16" },
    ],
    name: "setZeroTokenThresholdRatio",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "proposalId_", internalType: "uint256", type: "uint256" }],
    name: "state",
    outputs: [
      {
        name: "state_",
        internalType: "enum IGovernor.ProposalState",
        type: "uint8",
      },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "key_", internalType: "bytes32", type: "bytes32" },
      { name: "value_", internalType: "bytes32", type: "bytes32" },
    ],
    name: "updateConfig",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "vault",
    outputs: [{ name: "vault_", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "votingDelay",
    outputs: [
      { name: "votingDelay_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [],
    name: "votingPeriod",
    outputs: [
      { name: "votingPeriod_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "zeroToken",
    outputs: [{ name: "zeroToken_", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "zeroTokenThresholdRatio",
    outputs: [
      { name: "thresholdRatio_", internalType: "uint256", type: "uint256" },
    ],
  },
] as const;

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// PowerBootstrapToken
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const powerBootstrapTokenABI = [
  {
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [
      {
        name: "initialAccounts_",
        internalType: "address[]",
        type: "address[]",
      },
      {
        name: "initialBalances_",
        internalType: "uint256[]",
        type: "uint256[]",
      },
    ],
  },
  {
    type: "error",
    inputs: [
      { name: "accountsLength", internalType: "uint256", type: "uint256" },
      { name: "balancesLength", internalType: "uint256", type: "uint256" },
    ],
    name: "LengthMismatch",
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "epoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "balanceOfAt",
    outputs: [{ name: "balance_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "epoch_", internalType: "uint256", type: "uint256" }],
    name: "totalSupplyAt",
    outputs: [
      { name: "totalSupply_", internalType: "uint256", type: "uint256" },
    ],
  },
] as const;

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// PowerToken
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const powerTokenABI = [
  {
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [
      { name: "governor_", internalType: "address", type: "address" },
      { name: "cashToken_", internalType: "address", type: "address" },
      { name: "vault_", internalType: "address", type: "address" },
      { name: "bootstrapToken_", internalType: "address", type: "address" },
    ],
  },
  { type: "error", inputs: [], name: "AlreadyClaimed" },
  { type: "error", inputs: [], name: "AlreadyDelegated" },
  { type: "error", inputs: [], name: "AlreadyParticipated" },
  { type: "error", inputs: [], name: "AmountExceedsUint240" },
  { type: "error", inputs: [], name: "EpochAlreadyActive" },
  { type: "error", inputs: [], name: "InsufficientAuctionSupply" },
  { type: "error", inputs: [], name: "InvalidEpochOrdering" },
  { type: "error", inputs: [], name: "InvalidSignature" },
  { type: "error", inputs: [], name: "MalleableSignature" },
  { type: "error", inputs: [], name: "NotGovernor" },
  { type: "error", inputs: [], name: "NotVoteEpoch" },
  {
    type: "error",
    inputs: [
      { name: "nonce", internalType: "uint256", type: "uint256" },
      { name: "currentNonce", internalType: "uint256", type: "uint256" },
    ],
    name: "ReusedNonce",
  },
  {
    type: "error",
    inputs: [
      { name: "deadline", internalType: "uint256", type: "uint256" },
      { name: "timestamp", internalType: "uint256", type: "uint256" },
    ],
    name: "SignatureExpired",
  },
  {
    type: "error",
    inputs: [
      { name: "account", internalType: "address", type: "address" },
      { name: "signer", internalType: "address", type: "address" },
    ],
    name: "SignerMismatch",
  },
  { type: "error", inputs: [], name: "TransferFromFailed" },
  { type: "error", inputs: [], name: "TransferToSelf" },
  { type: "error", inputs: [], name: "VoteEpoch" },
  { type: "error", inputs: [], name: "ZeroCashTokenAddress" },
  { type: "error", inputs: [], name: "ZeroDecreaseAllowance" },
  { type: "error", inputs: [], name: "ZeroGovernorAddress" },
  { type: "error", inputs: [], name: "ZeroIncreaseAllowance" },
  { type: "error", inputs: [], name: "ZeroVaultAddress" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "spender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Approval",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "buyer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "cost",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Buy",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "delegator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "fromDelegate",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "toDelegate",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "DelegateChanged",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "delegate",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "previousBalance",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "newBalance",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "DelegateVotesChanged",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "epoch",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
    ],
    name: "EpochMarkedActive",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "recipient",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Transfer",
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [],
    name: "CLOCK_MODE",
    outputs: [{ name: "clockMode_", internalType: "string", type: "string" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "DELEGATION_TYPEHASH",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "DOMAIN_SEPARATOR",
    outputs: [
      { name: "domainSeparator_", internalType: "bytes32", type: "bytes32" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "INITIAL_SUPPLY",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "ONE",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "PERMIT_TYPEHASH",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "activeEpochs",
    outputs: [
      { name: "activeEpochs_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "spender_", internalType: "address", type: "address" },
    ],
    name: "allowance",
    outputs: [{ name: "allowance_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "amountToAuction",
    outputs: [
      { name: "amountToAuction_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "spender_", internalType: "address", type: "address" },
      { name: "amount_", internalType: "uint256", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ name: "success_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "account_", internalType: "address", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "balance_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "epoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "balanceOfAt",
    outputs: [{ name: "balance_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "epochs_", internalType: "uint256[]", type: "uint256[]" },
    ],
    name: "balancesOfAt",
    outputs: [
      { name: "balances_", internalType: "uint256[]", type: "uint256[]" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "startEpoch_", internalType: "uint256", type: "uint256" },
      { name: "endEpoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "balancesOfBetween",
    outputs: [
      { name: "balances_", internalType: "uint256[]", type: "uint256[]" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "bootstrapEpoch",
    outputs: [
      { name: "bootstrapEpoch_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "bootstrapToken",
    outputs: [
      { name: "bootstrapToken_", internalType: "address", type: "address" },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "amount_", internalType: "uint256", type: "uint256" },
      { name: "destination_", internalType: "address", type: "address" },
    ],
    name: "buy",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "cashToken",
    outputs: [{ name: "cashToken_", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "clock",
    outputs: [{ name: "clock_", internalType: "uint48", type: "uint48" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "decimals",
    outputs: [{ name: "decimals_", internalType: "uint8", type: "uint8" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "spender_", internalType: "address", type: "address" },
      { name: "subtractedAmount_", internalType: "uint256", type: "uint256" },
    ],
    name: "decreaseAllowance",
    outputs: [{ name: "success_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [{ name: "delegatee_", internalType: "address", type: "address" }],
    name: "delegate",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "delegatee_", internalType: "address", type: "address" },
      { name: "nonce_", internalType: "uint256", type: "uint256" },
      { name: "expiry_", internalType: "uint256", type: "uint256" },
      { name: "v_", internalType: "uint8", type: "uint8" },
      { name: "r_", internalType: "bytes32", type: "bytes32" },
      { name: "s_", internalType: "bytes32", type: "bytes32" },
    ],
    name: "delegateBySig",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "account_", internalType: "address", type: "address" }],
    name: "delegates",
    outputs: [{ name: "delegatee_", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "epoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "delegatesAt",
    outputs: [{ name: "delegatee_", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "amount_", internalType: "uint256", type: "uint256" }],
    name: "getCost",
    outputs: [{ name: "cost_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "epoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "getPastVotes",
    outputs: [
      { name: "votingPower_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "account_", internalType: "address", type: "address" }],
    name: "getVotes",
    outputs: [
      { name: "votingPower_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "governor",
    outputs: [{ name: "governor_", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "delegatee_", internalType: "address", type: "address" },
      { name: "epoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "hasParticipatedAt",
    outputs: [{ name: "participated_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "spender_", internalType: "address", type: "address" },
      { name: "addedAmount_", internalType: "uint256", type: "uint256" },
    ],
    name: "increaseAllowance",
    outputs: [{ name: "success_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "epoch_", internalType: "uint256", type: "uint256" }],
    name: "isActiveEpoch",
    outputs: [{ name: "isActiveEpoch_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [],
    name: "markEpochActive",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [{ name: "delegatee_", internalType: "address", type: "address" }],
    name: "markParticipation",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "name",
    outputs: [{ name: "name_", internalType: "string", type: "string" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "account_", internalType: "address", type: "address" }],
    name: "nonces",
    outputs: [{ name: "nonce_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "participationInflation",
    outputs: [
      {
        name: "participationInflation_",
        internalType: "uint256",
        type: "uint256",
      },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "owner_", internalType: "address", type: "address" },
      { name: "spender_", internalType: "address", type: "address" },
      { name: "amount_", internalType: "uint256", type: "uint256" },
      { name: "deadline_", internalType: "uint256", type: "uint256" },
      { name: "v_", internalType: "uint8", type: "uint8" },
      { name: "r_", internalType: "bytes32", type: "bytes32" },
      { name: "s_", internalType: "bytes32", type: "bytes32" },
    ],
    name: "permit",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "nextCashToken_", internalType: "address", type: "address" },
    ],
    name: "setNextCashToken",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "symbol",
    outputs: [{ name: "symbol_", internalType: "string", type: "string" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "epochs_", internalType: "uint256[]", type: "uint256[]" }],
    name: "totalSuppliesAt",
    outputs: [
      { name: "totalSupplies_", internalType: "uint256[]", type: "uint256[]" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "startEpoch_", internalType: "uint256", type: "uint256" },
      { name: "endEpoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "totalSuppliesBetween",
    outputs: [
      { name: "totalSupplies_", internalType: "uint256[]", type: "uint256[]" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "totalSupply",
    outputs: [
      { name: "totalSupply_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "epoch_", internalType: "uint256", type: "uint256" }],
    name: "totalSupplyAt",
    outputs: [
      { name: "totalSupply_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "recipient_", internalType: "address", type: "address" },
      { name: "amount_", internalType: "uint256", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ name: "success_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "sender_", internalType: "address", type: "address" },
      { name: "recipient_", internalType: "address", type: "address" },
      { name: "amount_", internalType: "uint256", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ name: "success_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "vault",
    outputs: [{ name: "vault_", internalType: "address", type: "address" }],
  },
] as const;

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Registrar
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const registrarABI = [
  {
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [
      { name: "governorDeployer_", internalType: "address", type: "address" },
      { name: "powerTokenDeployer_", internalType: "address", type: "address" },
      { name: "bootstrapToken_", internalType: "address", type: "address" },
    ],
  },
  { type: "error", inputs: [], name: "CallerIsNotGovernor" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "list", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "AddressAddedToList",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "list", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "AddressRemovedFromList",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "key", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "value",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
    ],
    name: "ConfigUpdated",
  },
  { type: "event", anonymous: false, inputs: [], name: "ResetExecuted" },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "list_", internalType: "bytes32", type: "bytes32" },
      { name: "account_", internalType: "address", type: "address" },
    ],
    name: "addToList",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "key_", internalType: "bytes32", type: "bytes32" }],
    name: "get",
    outputs: [{ name: "value_", internalType: "bytes32", type: "bytes32" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "keys_", internalType: "bytes32[]", type: "bytes32[]" }],
    name: "get",
    outputs: [
      { name: "values_", internalType: "bytes32[]", type: "bytes32[]" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "governor",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "governorDeployer",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "list_", internalType: "bytes32", type: "bytes32" },
      { name: "accounts_", internalType: "address[]", type: "address[]" },
    ],
    name: "listContains",
    outputs: [{ name: "contains_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "list_", internalType: "bytes32", type: "bytes32" },
      { name: "account_", internalType: "address", type: "address" },
    ],
    name: "listContains",
    outputs: [{ name: "contains_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "powerToken",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "powerTokenDeployer",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "list_", internalType: "bytes32", type: "bytes32" },
      { name: "account_", internalType: "address", type: "address" },
    ],
    name: "removeFromList",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "bootstrapToken_", internalType: "address", type: "address" },
    ],
    name: "reset",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "key_", internalType: "bytes32", type: "bytes32" },
      { name: "value_", internalType: "bytes32", type: "bytes32" },
    ],
    name: "updateConfig",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "vault",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "zeroToken",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
] as const;

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ZeroToken
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const zeroTokenABI = [
  {
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [
      { name: "registrar_", internalType: "address", type: "address" },
      {
        name: "initialAccounts_",
        internalType: "address[]",
        type: "address[]",
      },
      {
        name: "initialBalances_",
        internalType: "uint256[]",
        type: "uint256[]",
      },
    ],
  },
  { type: "error", inputs: [], name: "AlreadyDelegated" },
  { type: "error", inputs: [], name: "AmountExceedsUint240" },
  { type: "error", inputs: [], name: "InvalidEpochOrdering" },
  { type: "error", inputs: [], name: "InvalidSignature" },
  {
    type: "error",
    inputs: [
      { name: "length1", internalType: "uint256", type: "uint256" },
      { name: "length2", internalType: "uint256", type: "uint256" },
    ],
    name: "LengthMismatch",
  },
  { type: "error", inputs: [], name: "MalleableSignature" },
  { type: "error", inputs: [], name: "NotGovernor" },
  {
    type: "error",
    inputs: [
      { name: "nonce", internalType: "uint256", type: "uint256" },
      { name: "currentNonce", internalType: "uint256", type: "uint256" },
    ],
    name: "ReusedNonce",
  },
  {
    type: "error",
    inputs: [
      { name: "deadline", internalType: "uint256", type: "uint256" },
      { name: "timestamp", internalType: "uint256", type: "uint256" },
    ],
    name: "SignatureExpired",
  },
  {
    type: "error",
    inputs: [
      { name: "account", internalType: "address", type: "address" },
      { name: "signer", internalType: "address", type: "address" },
    ],
    name: "SignerMismatch",
  },
  { type: "error", inputs: [], name: "TransferToSelf" },
  { type: "error", inputs: [], name: "ZeroDecreaseAllowance" },
  { type: "error", inputs: [], name: "ZeroIncreaseAllowance" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "spender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Approval",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "delegator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "fromDelegate",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "toDelegate",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "DelegateChanged",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "delegate",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "previousBalance",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "newBalance",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "DelegateVotesChanged",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "recipient",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Transfer",
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [],
    name: "CLOCK_MODE",
    outputs: [{ name: "clockMode_", internalType: "string", type: "string" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "DELEGATION_TYPEHASH",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "DOMAIN_SEPARATOR",
    outputs: [
      { name: "domainSeparator_", internalType: "bytes32", type: "bytes32" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "PERMIT_TYPEHASH",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "spender_", internalType: "address", type: "address" },
    ],
    name: "allowance",
    outputs: [{ name: "allowance_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "spender_", internalType: "address", type: "address" },
      { name: "amount_", internalType: "uint256", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ name: "success_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "account_", internalType: "address", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "balance_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "epoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "balanceOfAt",
    outputs: [{ name: "balance_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "epochs_", internalType: "uint256[]", type: "uint256[]" },
    ],
    name: "balancesOfAt",
    outputs: [
      { name: "balances_", internalType: "uint256[]", type: "uint256[]" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "startEpoch_", internalType: "uint256", type: "uint256" },
      { name: "endEpoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "balancesOfBetween",
    outputs: [
      { name: "balances_", internalType: "uint256[]", type: "uint256[]" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "clock",
    outputs: [{ name: "clock_", internalType: "uint48", type: "uint48" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "decimals",
    outputs: [{ name: "decimals_", internalType: "uint8", type: "uint8" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "spender_", internalType: "address", type: "address" },
      { name: "subtractedAmount_", internalType: "uint256", type: "uint256" },
    ],
    name: "decreaseAllowance",
    outputs: [{ name: "success_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [{ name: "delegatee_", internalType: "address", type: "address" }],
    name: "delegate",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "delegatee_", internalType: "address", type: "address" },
      { name: "nonce_", internalType: "uint256", type: "uint256" },
      { name: "expiry_", internalType: "uint256", type: "uint256" },
      { name: "v_", internalType: "uint8", type: "uint8" },
      { name: "r_", internalType: "bytes32", type: "bytes32" },
      { name: "s_", internalType: "bytes32", type: "bytes32" },
    ],
    name: "delegateBySig",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "account_", internalType: "address", type: "address" }],
    name: "delegates",
    outputs: [{ name: "delegatee_", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "epoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "delegatesAt",
    outputs: [{ name: "delegatee_", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "account_", internalType: "address", type: "address" },
      { name: "epoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "getPastVotes",
    outputs: [
      { name: "votingPower_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "account_", internalType: "address", type: "address" }],
    name: "getVotes",
    outputs: [
      { name: "votingPower_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "spender_", internalType: "address", type: "address" },
      { name: "addedAmount_", internalType: "uint256", type: "uint256" },
    ],
    name: "increaseAllowance",
    outputs: [{ name: "success_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "recipient_", internalType: "address", type: "address" },
      { name: "amount_", internalType: "uint256", type: "uint256" },
    ],
    name: "mint",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "name",
    outputs: [{ name: "name_", internalType: "string", type: "string" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "account_", internalType: "address", type: "address" }],
    name: "nonces",
    outputs: [{ name: "nonce_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "owner_", internalType: "address", type: "address" },
      { name: "spender_", internalType: "address", type: "address" },
      { name: "amount_", internalType: "uint256", type: "uint256" },
      { name: "deadline_", internalType: "uint256", type: "uint256" },
      { name: "v_", internalType: "uint8", type: "uint8" },
      { name: "r_", internalType: "bytes32", type: "bytes32" },
      { name: "s_", internalType: "bytes32", type: "bytes32" },
    ],
    name: "permit",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "registrar",
    outputs: [{ name: "registrar_", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "symbol",
    outputs: [{ name: "symbol_", internalType: "string", type: "string" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "epochs_", internalType: "uint256[]", type: "uint256[]" }],
    name: "totalSuppliesAt",
    outputs: [
      { name: "totalSupplies_", internalType: "uint256[]", type: "uint256[]" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "startEpoch_", internalType: "uint256", type: "uint256" },
      { name: "endEpoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "totalSuppliesBetween",
    outputs: [
      { name: "totalSupplies_", internalType: "uint256[]", type: "uint256[]" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "totalSupply",
    outputs: [
      { name: "totalSupply_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "epoch_", internalType: "uint256", type: "uint256" }],
    name: "totalSupplyAt",
    outputs: [
      { name: "totalSupply_", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "recipient_", internalType: "address", type: "address" },
      { name: "amount_", internalType: "uint256", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ name: "success_", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "sender_", internalType: "address", type: "address" },
      { name: "recipient_", internalType: "address", type: "address" },
      { name: "amount_", internalType: "uint256", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ name: "success_", internalType: "bool", type: "bool" }],
  },
] as const;

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DistributionVault
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const distributionVaultABI = [
  {
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [{ name: "baseToken_", internalType: "address", type: "address" }],
  },
  { type: "error", inputs: [], name: "AlreadyClaimed" },
  { type: "error", inputs: [], name: "EpochTooHigh" },
  { type: "error", inputs: [], name: "TransferFailed" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "epoch",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Claim",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "epoch",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Distribution",
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "baseToken",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "token_", internalType: "address", type: "address" },
      { name: "startEpoch_", internalType: "uint256", type: "uint256" },
      { name: "endEpoch_", internalType: "uint256", type: "uint256" },
      { name: "destination_", internalType: "address", type: "address" },
    ],
    name: "claim",
    outputs: [{ name: "claimed_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "token_", internalType: "address", type: "address" },
      { name: "epoch_", internalType: "uint256", type: "uint256" },
      { name: "destination_", internalType: "address", type: "address" },
    ],
    name: "claim",
    outputs: [{ name: "claimed_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "token_", internalType: "address", type: "address" },
      { name: "epochs_", internalType: "uint256[]", type: "uint256[]" },
      { name: "destination_", internalType: "address", type: "address" },
    ],
    name: "claim",
    outputs: [{ name: "claimed_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "token_", internalType: "address", type: "address" },
      { name: "account_", internalType: "address", type: "address" },
      { name: "epoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "claimableOfAt",
    outputs: [{ name: "claimable_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "token_", internalType: "address", type: "address" },
      { name: "account_", internalType: "address", type: "address" },
      { name: "epochs_", internalType: "uint256[]", type: "uint256[]" },
    ],
    name: "claimableOfAt",
    outputs: [{ name: "claimable_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "token_", internalType: "address", type: "address" },
      { name: "account_", internalType: "address", type: "address" },
      { name: "startEpoch_", internalType: "uint256", type: "uint256" },
      { name: "endEpoch_", internalType: "uint256", type: "uint256" },
    ],
    name: "claimableOfBetween",
    outputs: [{ name: "claimable_", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [{ name: "token_", internalType: "address", type: "address" }],
    name: "distribute",
    outputs: [],
  },
] as const;

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Core
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link getContract}__ with `abi` set to __{@link dualGovernorABI}__.
 */
export function getDualGovernor(config: Omit<GetContractArgs, "abi">) {
  return getContract({ abi: dualGovernorABI, ...config });
}

/**
 * Wraps __{@link readContract}__ with `abi` set to __{@link dualGovernorABI}__.
 */
export function readDualGovernor<
  TAbi extends readonly unknown[] = typeof dualGovernorABI,
  TFunctionName extends string = string
>(config: Omit<ReadContractConfig<TAbi, TFunctionName>, "abi">) {
  return readContract({
    abi: dualGovernorABI,
    ...config,
  } as unknown as ReadContractConfig<TAbi, TFunctionName>);
}

/**
 * Wraps __{@link writeContract}__ with `abi` set to __{@link dualGovernorABI}__.
 */
export function writeDualGovernor<TFunctionName extends string>(
  config:
    | Omit<
        WriteContractPreparedArgs<typeof dualGovernorABI, TFunctionName>,
        "abi"
      >
    | Omit<
        WriteContractUnpreparedArgs<typeof dualGovernorABI, TFunctionName>,
        "abi"
      >
) {
  return writeContract({ abi: dualGovernorABI, ...config } as WriteContractArgs<
    typeof dualGovernorABI,
    TFunctionName
  >);
}

/**
 * Wraps __{@link prepareWriteContract}__ with `abi` set to __{@link dualGovernorABI}__.
 */
export function prepareWriteDualGovernor<
  TAbi extends readonly unknown[] = typeof dualGovernorABI,
  TFunctionName extends string = string
>(config: Omit<PrepareWriteContractConfig<TAbi, TFunctionName>, "abi">) {
  return prepareWriteContract({
    abi: dualGovernorABI,
    ...config,
  } as unknown as PrepareWriteContractConfig<TAbi, TFunctionName>);
}

/**
 * Wraps __{@link watchContractEvent}__ with `abi` set to __{@link dualGovernorABI}__.
 */
export function watchDualGovernorEvent<
  TAbi extends readonly unknown[] = typeof dualGovernorABI,
  TEventName extends string = string
>(
  config: Omit<WatchContractEventConfig<TAbi, TEventName>, "abi">,
  callback: WatchContractEventCallback<TAbi, TEventName>
) {
  return watchContractEvent(
    { abi: dualGovernorABI, ...config } as WatchContractEventConfig<
      TAbi,
      TEventName
    >,
    callback
  );
}

/**
 * Wraps __{@link getContract}__ with `abi` set to __{@link powerBootstrapTokenABI}__.
 */
export function getPowerBootstrapToken(config: Omit<GetContractArgs, "abi">) {
  return getContract({ abi: powerBootstrapTokenABI, ...config });
}

/**
 * Wraps __{@link readContract}__ with `abi` set to __{@link powerBootstrapTokenABI}__.
 */
export function readPowerBootstrapToken<
  TAbi extends readonly unknown[] = typeof powerBootstrapTokenABI,
  TFunctionName extends string = string
>(config: Omit<ReadContractConfig<TAbi, TFunctionName>, "abi">) {
  return readContract({
    abi: powerBootstrapTokenABI,
    ...config,
  } as unknown as ReadContractConfig<TAbi, TFunctionName>);
}

/**
 * Wraps __{@link getContract}__ with `abi` set to __{@link powerTokenABI}__.
 */
export function getPowerToken(config: Omit<GetContractArgs, "abi">) {
  return getContract({ abi: powerTokenABI, ...config });
}

/**
 * Wraps __{@link readContract}__ with `abi` set to __{@link powerTokenABI}__.
 */
export function readPowerToken<
  TAbi extends readonly unknown[] = typeof powerTokenABI,
  TFunctionName extends string = string
>(config: Omit<ReadContractConfig<TAbi, TFunctionName>, "abi">) {
  return readContract({
    abi: powerTokenABI,
    ...config,
  } as unknown as ReadContractConfig<TAbi, TFunctionName>);
}

/**
 * Wraps __{@link writeContract}__ with `abi` set to __{@link powerTokenABI}__.
 */
export function writePowerToken<TFunctionName extends string>(
  config:
    | Omit<
        WriteContractPreparedArgs<typeof powerTokenABI, TFunctionName>,
        "abi"
      >
    | Omit<
        WriteContractUnpreparedArgs<typeof powerTokenABI, TFunctionName>,
        "abi"
      >
) {
  return writeContract({ abi: powerTokenABI, ...config } as WriteContractArgs<
    typeof powerTokenABI,
    TFunctionName
  >);
}

/**
 * Wraps __{@link prepareWriteContract}__ with `abi` set to __{@link powerTokenABI}__.
 */
export function prepareWritePowerToken<
  TAbi extends readonly unknown[] = typeof powerTokenABI,
  TFunctionName extends string = string
>(config: Omit<PrepareWriteContractConfig<TAbi, TFunctionName>, "abi">) {
  return prepareWriteContract({
    abi: powerTokenABI,
    ...config,
  } as unknown as PrepareWriteContractConfig<TAbi, TFunctionName>);
}

/**
 * Wraps __{@link watchContractEvent}__ with `abi` set to __{@link powerTokenABI}__.
 */
export function watchPowerTokenEvent<
  TAbi extends readonly unknown[] = typeof powerTokenABI,
  TEventName extends string = string
>(
  config: Omit<WatchContractEventConfig<TAbi, TEventName>, "abi">,
  callback: WatchContractEventCallback<TAbi, TEventName>
) {
  return watchContractEvent(
    { abi: powerTokenABI, ...config } as WatchContractEventConfig<
      TAbi,
      TEventName
    >,
    callback
  );
}

/**
 * Wraps __{@link getContract}__ with `abi` set to __{@link registrarABI}__.
 */
export function getRegistrar(config: Omit<GetContractArgs, "abi">) {
  return getContract({ abi: registrarABI, ...config });
}

/**
 * Wraps __{@link readContract}__ with `abi` set to __{@link registrarABI}__.
 */
export function readRegistrar<
  TAbi extends readonly unknown[] = typeof registrarABI,
  TFunctionName extends string = string
>(config: Omit<ReadContractConfig<TAbi, TFunctionName>, "abi">) {
  return readContract({
    abi: registrarABI,
    ...config,
  } as unknown as ReadContractConfig<TAbi, TFunctionName>);
}

/**
 * Wraps __{@link writeContract}__ with `abi` set to __{@link registrarABI}__.
 */
export function writeRegistrar<TFunctionName extends string>(
  config:
    | Omit<WriteContractPreparedArgs<typeof registrarABI, TFunctionName>, "abi">
    | Omit<
        WriteContractUnpreparedArgs<typeof registrarABI, TFunctionName>,
        "abi"
      >
) {
  return writeContract({ abi: registrarABI, ...config } as WriteContractArgs<
    typeof registrarABI,
    TFunctionName
  >);
}

/**
 * Wraps __{@link prepareWriteContract}__ with `abi` set to __{@link registrarABI}__.
 */
export function prepareWriteRegistrar<
  TAbi extends readonly unknown[] = typeof registrarABI,
  TFunctionName extends string = string
>(config: Omit<PrepareWriteContractConfig<TAbi, TFunctionName>, "abi">) {
  return prepareWriteContract({
    abi: registrarABI,
    ...config,
  } as unknown as PrepareWriteContractConfig<TAbi, TFunctionName>);
}

/**
 * Wraps __{@link watchContractEvent}__ with `abi` set to __{@link registrarABI}__.
 */
export function watchRegistrarEvent<
  TAbi extends readonly unknown[] = typeof registrarABI,
  TEventName extends string = string
>(
  config: Omit<WatchContractEventConfig<TAbi, TEventName>, "abi">,
  callback: WatchContractEventCallback<TAbi, TEventName>
) {
  return watchContractEvent(
    { abi: registrarABI, ...config } as WatchContractEventConfig<
      TAbi,
      TEventName
    >,
    callback
  );
}

/**
 * Wraps __{@link getContract}__ with `abi` set to __{@link zeroTokenABI}__.
 */
export function getZeroToken(config: Omit<GetContractArgs, "abi">) {
  return getContract({ abi: zeroTokenABI, ...config });
}

/**
 * Wraps __{@link readContract}__ with `abi` set to __{@link zeroTokenABI}__.
 */
export function readZeroToken<
  TAbi extends readonly unknown[] = typeof zeroTokenABI,
  TFunctionName extends string = string
>(config: Omit<ReadContractConfig<TAbi, TFunctionName>, "abi">) {
  return readContract({
    abi: zeroTokenABI,
    ...config,
  } as unknown as ReadContractConfig<TAbi, TFunctionName>);
}

/**
 * Wraps __{@link writeContract}__ with `abi` set to __{@link zeroTokenABI}__.
 */
export function writeZeroToken<TFunctionName extends string>(
  config:
    | Omit<WriteContractPreparedArgs<typeof zeroTokenABI, TFunctionName>, "abi">
    | Omit<
        WriteContractUnpreparedArgs<typeof zeroTokenABI, TFunctionName>,
        "abi"
      >
) {
  return writeContract({ abi: zeroTokenABI, ...config } as WriteContractArgs<
    typeof zeroTokenABI,
    TFunctionName
  >);
}

/**
 * Wraps __{@link prepareWriteContract}__ with `abi` set to __{@link zeroTokenABI}__.
 */
export function prepareWriteZeroToken<
  TAbi extends readonly unknown[] = typeof zeroTokenABI,
  TFunctionName extends string = string
>(config: Omit<PrepareWriteContractConfig<TAbi, TFunctionName>, "abi">) {
  return prepareWriteContract({
    abi: zeroTokenABI,
    ...config,
  } as unknown as PrepareWriteContractConfig<TAbi, TFunctionName>);
}

/**
 * Wraps __{@link watchContractEvent}__ with `abi` set to __{@link zeroTokenABI}__.
 */
export function watchZeroTokenEvent<
  TAbi extends readonly unknown[] = typeof zeroTokenABI,
  TEventName extends string = string
>(
  config: Omit<WatchContractEventConfig<TAbi, TEventName>, "abi">,
  callback: WatchContractEventCallback<TAbi, TEventName>
) {
  return watchContractEvent(
    { abi: zeroTokenABI, ...config } as WatchContractEventConfig<
      TAbi,
      TEventName
    >,
    callback
  );
}

/**
 * Wraps __{@link getContract}__ with `abi` set to __{@link distributionVaultABI}__.
 */
export function getDistributionVault(config: Omit<GetContractArgs, "abi">) {
  return getContract({ abi: distributionVaultABI, ...config });
}

/**
 * Wraps __{@link readContract}__ with `abi` set to __{@link distributionVaultABI}__.
 */
export function readDistributionVault<
  TAbi extends readonly unknown[] = typeof distributionVaultABI,
  TFunctionName extends string = string
>(config: Omit<ReadContractConfig<TAbi, TFunctionName>, "abi">) {
  return readContract({
    abi: distributionVaultABI,
    ...config,
  } as unknown as ReadContractConfig<TAbi, TFunctionName>);
}

/**
 * Wraps __{@link writeContract}__ with `abi` set to __{@link distributionVaultABI}__.
 */
export function writeDistributionVault<TFunctionName extends string>(
  config:
    | Omit<
        WriteContractPreparedArgs<typeof distributionVaultABI, TFunctionName>,
        "abi"
      >
    | Omit<
        WriteContractUnpreparedArgs<typeof distributionVaultABI, TFunctionName>,
        "abi"
      >
) {
  return writeContract({
    abi: distributionVaultABI,
    ...config,
  } as WriteContractArgs<typeof distributionVaultABI, TFunctionName>);
}

/**
 * Wraps __{@link prepareWriteContract}__ with `abi` set to __{@link distributionVaultABI}__.
 */
export function prepareWriteDistributionVault<
  TAbi extends readonly unknown[] = typeof distributionVaultABI,
  TFunctionName extends string = string
>(config: Omit<PrepareWriteContractConfig<TAbi, TFunctionName>, "abi">) {
  return prepareWriteContract({
    abi: distributionVaultABI,
    ...config,
  } as unknown as PrepareWriteContractConfig<TAbi, TFunctionName>);
}

/**
 * Wraps __{@link watchContractEvent}__ with `abi` set to __{@link distributionVaultABI}__.
 */
export function watchDistributionVaultEvent<
  TAbi extends readonly unknown[] = typeof distributionVaultABI,
  TEventName extends string = string
>(
  config: Omit<WatchContractEventConfig<TAbi, TEventName>, "abi">,
  callback: WatchContractEventCallback<TAbi, TEventName>
) {
  return watchContractEvent(
    { abi: distributionVaultABI, ...config } as WatchContractEventConfig<
      TAbi,
      TEventName
    >,
    callback
  );
}
