name: Build & Upload to S3 DEV

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: m0-foundation/ttg-frontend/.github/workflows/s3_buckets_build_and_upload_dev.yml@main
    secrets: inherit
    permissions:
      contents: write
    if: github.ref_name == 'main'
